### ISSUE TITLE
Isn't your concept close to loopback.io philosophy ?

### ISSUE THREAD

**Issue by tornad** [nfroidure/whook#2]
Hi,

I'm not sure to have understand all the goal's of the concept that's you're describing, but for me, it's look like the loopback.io model's concept.

Did you have test/explore there API/OBJECT/MODEL API of lookpack ? 

I have select some links in tutorial for short read for you if you want to have look.

Here's the model's extending for specific function... which could be mapped or not to REST endpoint.
- http://docs.strongloop.com/display/public/LB/Remote+methods

The application logic (not clear at the first read but example helps)
- http://docs.strongloop.com/display/public/LB/Adding+application+logic

Here's a model example with REST or not that use the user model for registering user ... 
Model is not build for REST API; it's standalone class that could be test without REST.
- http://docs.strongloop.com/display/public/LB/Registering+users

Regards,

**Comment by tornad** [comment]
One good point for whook is that all the declarative stuff, config, link seems to be in the whook. As loopback need to create multiple files for handling a model. For a car's class, you need:
models/cars.json   => class property/links/acls/validation
models/cars.js => pre/post/specific functions and hooks
I have not check/try to see  if it's could be group in a single file easily..

**Comment by nfroidure** [comment]
It's amazing to see how the two APIs look similar :). Someone also pointed me out contracts http://disnetdev.com/contracts.js/ .

There is a fundamental difference though. The HTTP to remote method mapping seems to only concern the input/request and not the output/response.

Also, i like the mapping idea, but don't want to suscribe to a whole architecture for this sole benefit ;).

Thank you for the links anyway, it helped me a lot!

I'm currently also looking at swagger. I'm wondering how i could merge Whook specs with a swagger schema or at least output a swagger schema from specs.

**Comment by nfroidure** [comment]
Forgot, but seems essential to me, request/response mapping to hooks input/output should allow async resolution, it seems sync only with the strongloop API.
