### ISSUE TITLE
I/O streams

### ISSUE THREAD

**Issue by nfroidure** [nfroidure/whook#7]
When response headers and in particular response code are sent, it means the transaction were well threated so, i assume that the request stream should be completely consumed before sending headers.

For this reason, i'm wondering if the `Whook#process` method shouldn't be splitted into `Whook#processInput` and `Whook#processOuput` ones. That way, any whook could add transform streams to the in/out pipelines.

**Comment by nfroidure** [comment]
Modifying Router.add() to accept Whook constructors instead of Whook instances ?

**Comment by nfroidure** [comment]
Last thoughts:

HTTP transactions should involve the following steps:
- consume and verify request headers and input stream. As a result produce the response headers (acknowledge the fact the request has been completed per the system).
- produce an output stream if you eventually need to produce a representation.

Whook should so just have two methods for those two steps.

Since a good architecture acknowledge only when you are sure to compute any trigger involved per any modificative request, Whook should not handle post HTTP transaction actions and let message queue brokers handle this job. So we should just remove the post hooks.

cc @SebastienElet

**Comment by SebastienElet** [comment]
I agree, this is not the responsability of the web server to handle post HTTP actions.

This could be done with a message broker or any queue system / job manager.
